//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountryNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int id { get; set; }
        public string NameCunrtry { get; set; }
        public string NameCunrtryEN { get; set; }
        public int Cod { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual CodTable CodTable { get; set; }
    }
}
